MCU          = atmega328p
F_CPU        = 16000000UL
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS := Adafruit_TFTLCD Adafruit_GFX TouchScreen

AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE_ARD_BAUDRATE   = 115200

USER_LIB_PATH := $(realpath ../../libraries)


include /usr/share/arduino/Arduino.mk


